services:
  app:
    container_name: mtrucklending
    image: ghcr.io/makmillerme/mtruck-lending:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "3002:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    volumes:
      - ./data:/app/data
